#!/bin/sh
#
# @name Esky (Big) Lama v4
#
# @type Coaxial Helicopter
# @class Copter
#
# @output MAIN1 Left swashplate servomotor, pitch axis
# @output MAIN2 Right swashplate servomotor, roll axis
# @output MAIN3 Upper rotor (CCW)
# @output MAIN4 Lower rotor (CW)
#
# @maintainer Emmanuel Roussel
#
# @board px4_fmu-v2 exclude
# @board intel_aerofc-v1 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.mc_defaults



param set-default MC_ROLL_P 6.5
param set-default MC_ROLLRATE_P 0.45
param set-default MC_ROLLRATE_I 0.1
param set-default MC_ROLLRATE_D 0.01
param set-default MC_ROLLRATE_FF 0
param set-default MC_PITCH_P 6.5
param set-default MC_PITCHRATE_P 0.45
param set-default MC_PITCHRATE_I 0.05
param set-default MC_PITCHRATE_D 0.01
param set-default MC_PITCHRATE_FF 0
param set-default MC_YAW_P 2
param set-default MC_YAWRATE_P 0.3
param set-default MC_YAWRATE_I 0.05
param set-default MC_YAWRATE_D 0
param set-default MC_YAWRATE_FF 0




set MAV_TYPE 3

set MIXER ductedfan2
